{% set name = "pysmi" %}
{% set version = "1.5.9" %}
{% set sha256 = "f6dfda838e3cba133169f1ff57f71a2841815d43db2e5c619b6e5db3b8560707" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python
    - ply <4.0,>=3.11
    - jinja2 <4.0.0,>=3.1.3
    - requests <3.0.0,>=2.26.0

test:
  imports:
    - pysmi
    - pysmi.borrower
    - pysmi.codegen
    - pysmi.lexer
    - pysmi.parser
    - pysmi.reader
    - pysmi.searcher
    - pysmi.writer
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.pysnmp.com/pysmi/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP SMI/MIB Parser
  description: 'A pure-Python implementation of SNMP/SMI MIB parsing and conversion library.'
  doc_url: https://docs.lextudio.com/pysmi/
  dev_url: https://github.com/lextudio/pysmi

extra:
  recipe-maintainers:
    - nehaljwani