travis:
  secure:
    BINSTAR_TOKEN: ALLh3s+0gVAtDB1TEqmPTt8xrMa3aJGxx+pMHihPo/ZWpK/XjiuNfSbiOC4cZhw1ZdO2D5wxW2VHue8CW/oykhN0UPIr5eh4IDYcLTM3LsohWYO+2gpM7pfLpqqhPFz/DmHd9hqeI5Kdp+qnuAL3XcrYCbO2CNHkN9awXBWPRuYpNelAxalDnCKRO1IRJO6nUkVZmrXlVWZ0sQwVVMDLcaCDhK2Pt4Z4Wn5nZTPTJXBXNfFcW51XiAvofu9OF6H5adrx1PbG+pukmKwvcBBdxAML4TKq1s0woYAzhwQL+kRvO9LoAzl/S7w78ZKZxcgt1GMg8Xt2IYju1MUH+szdegt2jwnEZWb+a+AEyYD51DLJtIPRgNp/Mp4MaAHgwrriQYSkNSkpQFF/W+mmvVtgGLJe587bWJzzavzE8a52b39N3m0NyxWZOZvED6tKq7arrGGUP6+8oONOedZud25TM0vkAHjYAKvGjLlOvOjfWdqojVmqBCC9XGB5/JVfUYY6RwjRA190U+w2ENxaDgDc9ScMfbiFMJEkdayTMNRQ5JEjKyKCWstYCwqS41djrgxfONmII+BCQJGD/eNtycZ1w1WMVwh/mOvHnF3QEqTKOMbframFVl9ZjRgDAjVs64N+43Lz3WmqupS0VX+dPjkRW3If25kDJx1YsVlJuAS6Ez8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
