travis:
  secure:
    BINSTAR_TOKEN: UdZ1XEyCB0GcCFah13vrwnaJKEDma26qg7/Fv9/Di3dv8iwgLO/eCnO04J3b6jfsK1hFOJh6/5PDcCl87MVxjFQFVllBFy+Np6gd8eZhNA+tureRlKGJQtHSWdGn5EEqEtGJMuV4VRbeaxcXVT/2jH5cRUDoTs10GT2TGyDQV9CJiaAO5yxlFyalgCdQ1vA2G2Uko+2uX/W7WjUUnlimW4687QIrSChvuk8U27feDfY5dZzid/T+G7uPWNFUdQmYcdYfuwRgEYcOJjzIPgKSq0/GHxIZkgDiTAi434KmIc7VBG8DhDkzkLo29tfw8MkEF1jV6/vKOJVt1I3LrUtuGI1edRFV3kWMITKl+cWVNCtBsBGoWY4nmDTwDxVgwRyLF0XHIv1N0KtVoS2FUBDdPW6+4S5zfgJE+3SqAN6tbgAh/C49sLdlpvMwRnVM194j7OAZ/zkWGyp9ZbddrJDVE0i6zKB/HYnaVE5fBH5FIgyGa++Dgcrt9IhwQHAQO/VE4nVm7w//ByCF+FIiUDqdRfFH7pmrVdOeYkBe+JThH5MMligVrIZMZ7LtAab4PaVO8IE99Ctm9P4jQH74ntD10BqARmicux2YO8pylndIfplP4kYPNFo0p36d7U3fkiVBTexvQvveJ/FEyojbai09v3PHqlsiYy+jMHF6exhs0g4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
